### ISSUE TITLE
Cannot use 'String' as class name as it is reserved - PHP 7

### ISSUE THREAD

**Issue by scrnet** [zendframework/zend-xmlrpc#18]
I'm trying to include zend-xmlrpc in a Symfony2 project running in PHP 7 and I'm having this Compile Error:
Compile Error: Cannot use 'String' as class name as it is reserved

**Comment by weierophinney** [comment]
Can you please provide:
- the full error details
- minimal code to reproduce

We've been successfully testing this component against php 7 for over a year now, so we need more details to understand how these compile errors occur.

Thanks!

**Comment by scrnet** [comment]
I'm using an old version fro zend-xmlprc. Sorry.
