### ISSUE TITLE
Cannot interact with XMLRPC servers that use untrusted (self-signed) SSL certificates

### ISSUE THREAD

**Issue by phasetwo** [zendframework/zend-xmlrpc#26]
Hi,
when I try to interact with an XMLRPC server that has a self-signed SSL certificate (untrusted), I catch the following error:

`Fatal error: Uncaught ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/html/xmlrpc/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:303 Stack trace: #0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'stream_socket_e...', '/var/www/html/x...', 303, Array) #1 /var/www/html/xmlrpc/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php(303): stream_socket_enable_crypto(Resource id #2, true, 57) #2 /var/www/html/xmlrpc/vendor/zendframework/zend-http/src/Client.php(1412): Zend\Http\Client\Adapter\Socket->connect('localhost...', 50022, true) #3 /var/www/html/xmlrpc/vendor/zendframework/zend-http/src/Client.php(924): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'POST', true, Array, '<?xml version="...') #4 /var/www/html/xmlrpc/vendor/zendframework/zend-xmlrpc/src/Client.php(219): Zend\Http\Client->send() #5 /var/www/html/xmlrpc/vendor/zendfr in /var/www/html/xmlrpc/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php on line 332`

Is there any way to pass a flag that certificate checks are skipped?
Currently, I could not find any answers in the docs and was not able to fix it on my own.

**Comment by Ocramius** [comment]
@phasetwo you can configure [your HTTP client](https://github.com/zendframework/zend-xmlrpc/blob/c2cac5d44b1b8cf00e21be3a840850ea2b0b038f/src/Client.php#L27-L31) to use the correct SSL setup. See https://docs.zendframework.com/zend-http/client/adapters/#the-socket-adapter
