### ISSUE TITLE
read timed out after 10 seconds

### ISSUE THREAD

**Issue by evenloooo** [zendframework/zend-xmlrpc#37]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-xmlrpc/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-xmlrpc/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue
```php
$client = new \Zend\XmlRpc\Client('http://api.xxxxx.com');
```

### Expected results
No Timed out error...

### Actual results
TimeoutException in socket.php line 632: read timed out after 10 seconds

- in Socket.php line 632
- at Socket->_checkSocketReadTimeout() in Socket.php line 436
- at Socket->read() in Client.php line 1455
- at Client->doRequest(object(Http), 'POST', false, array('Host' => 'api.benchmarkemail.com', 'Connection' => 'close', 'Accept-Encoding' => 'gzip, deflate', 'Content-Type' => 'text/xml; charset=utf-8', 'Content-Length' => '41194', 'Accept' => 'text/xml', 'User-Agent' => 'Zend_XmlRpc_Client', 'Cookie' => 'ASP.NET_SessionId=25mmhyng1biinl4tu2qgspkk'), '<?xml version="1.0" encoding="UTF-8"?> <methodCall><methodName>xxxxxx ....

- at Client->send() in Client.php line 228
- at Client->doRequest(object(Request)) in Client.php line 318

**Comment by froschdesign** [comment]
@evenloooo
You can set the `timeout` option. Example:

```php
$client = new Zend\XmlRpc\Client('http://api.xxxxx.com');
$client->getHttpClient()->setOptions(['timeout' => 60]);
```

[`10` is the default value.](https://github.com/zendframework/zend-http/blob/9812b6e14b8e94ac0bfaece955bc863df2fcf309/src/Client.php#L110)

**Comment by evenloooo** [comment]
@froschdesign 

I didn't find any timeout setting on doc, so I post this issue.

Thank you so much!!!

**Comment by froschdesign** [comment]
@evenloooo 
The client from zend-http is used and there can you find the option: https://docs.zendframework.com/zend-http/client/intro/#quick-start

You are welcome!

**Comment by evenloooo** [comment]
@froschdesign 

Sorry for waste your time. I'll read it in detail.
Have a nice day!

**Comment by froschdesign** [comment]
> Sorry for waste your time.

No no, all fine! 😃
